### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [int-it/bdd-final1#19]
- [ ] Создать свой шаг проверяющий текст предупреждения

**Comment by alehinsasha** [comment]
Обычно это шаг проверяющий сообщения пользователю. Например, если после проведения реализации нет сообщений с текстом <какой-то текст> то реализация провелась корректно. Или наоборот есть текст если проверяем списание в минус.

**Comment by asosnoviy** [comment]
Проблема ясна. Сейчас [шаг](https://github.com/int-it/bdd-final1/blob/master/features/%D0%9F%D1%80%D0%BE%D0%B4%D0%B0%D0%B6%D0%B8/%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8C%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%BE%D0%B2%D0%9F%D1%80%D0%B8%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.feature#L47) проверяет провелся ли документ.  
Добавлю шаг перед ним `Тогда я получаю сообщение об ошибке с текстом "Недостаточно товара"`
