### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [int-it/bdd-final1#21]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by asosnoviy** [comment]
Алексею Сосновому  
int-it@yandex.ru

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by asosnoviy** [comment]
Письмо пришло, спасибо!

**Comment by alehinsasha** [comment]
готово!
